services:
  rdgen:
    # use bryangerlach/rdgen:latest for the latest build
    #build: .
    image: bryangerlach/rdgen:latest
    restart: unless-stopped
    environment:
      SECRET_KEY: "django-insecure-!(t-!f#6g#sr%yfded9(xha)g+=!6craeez^cp+*&bz_7vdk61"
      GHUSER: "Boxxxy"
      GHBEARER: "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"
      GENURL: "https://rdgen.hostname.com"
      ZIP_PASSWORD: "plok4er08"
      GHBRANCH: "master"
      PROTOCOL: "https"
      REPONAME: "rdgen"
      SH_SECRET: ""
    ports:
      - "8000:8000"
    dns:
      - 8.8.8.8
